config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  root to: 'welcome#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :admin do
    get 'landing', to: 'landing#index'

    resources :players
    resources :users
  end

  resources :pairings, only: [:edit, :update, :create, :destroy]
  resources :games, only: [:edit, :update]

  resources :schools, only: [:edit, :update, :index]
  resources :sports do
    resources :tournaments
  end

  resources :tournaments do
    resources :teams
  end
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :tournaments, dependent: :destroy

  validates_presence_of :name

  SOCCER = "Fútbol"
  INDOOR_FOOTBALL = "Fútbol Sala"
  BASKETBALL = "Básquetbol"
  VOLLEYBALL = "Vóleibol"
  BASEBALL = "Béisbol"
  PING_PONG = "Ping Pong"

  SPORTS = [
    SOCCER,
    INDOOR_FOOTBALL,
    BASKETBALL,
    VOLLEYBALL,
    BASEBALL,
    PING_PONG
  ]
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: [:edit, :update, :show, :destroy]
  # before_action :tournament_search, only: [:show]
  before_action :authenticate_user!

  def new
    @sport = Sport.new
  end

  def create
    @sport = Sport.new(sport_params)

    if @sport.save
      redirect_to sports_path, notice: 'Deporte creado correctamente'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @sport.update(sport_params)
      redirect_to sports_path, notice: 'Deporte actualizado correctamente'
    else
      render :edit
    end
  end

  def show
  end

  def index
    @sports = Sport.all
  end

  def destroy
    @sport.destroy
    redirect_to sports_path, alert: 'Deporte eliminado correctamente'
  end

  private

    def sport_params
      params.require(:sport).permit(:name)
    end

    def set_sport
      @sport = Sport.find(params[:id])
    end

    # def tournament_search
    #   @tournament = Tournament.where("sport_id = ?", params[:id])
    # end
end

app/views/sports/_form.html.erb
<%= render 'shared/errors', obj: @sport %>

<%= form_for @sport do |f| %>
  <div class="row justify-content-sm-center">
    <div class="col-sm-4">
      <div class="form-group">
        <%= f.label :name, "Nombre del Deporte" %>
        <%= f.text_field :name, class: "form-control", placeholder: "Ej.: Rugby" %>
      </div>
    </div>
  </div>

  <div class="row justify-content-sm-center">
    <div class="col-sm-4">
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/sports/edit.html.erb
<% provide(:button_text, "Editar") %>

<h1 align="center">Editar Deporte</h1>

<%= render "form" %>

app/views/sports/index.html.erb
<h1 align="center">Todos los Deportes</h1>

<div class="row justify-content-sm-center">
  <div class="col-sm-6">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Deporte</th>
          <th scope="col" style="text-align: center;">Cantidad de Torneos</th>
          <th scope="col" style="text-align: right;">
            <%= link_to "Agregar Deporte", new_sport_path, class: "btn btn-primary btn-sm" %>
          </th>
        </tr>
      </thead>

      <tbody>
        <% @sports.each do |sport| %>
          <tr>
            <td><%= sport.name %></td>
            <td style="text-align: center;"><%= sport.tournaments.count %></td>
            <td style="text-align: right;">
              <div class="btn-group" role="group" aria-label="User management">
                <%= link_to "Ver", sport, class: "btn btn-info btn-sm", type: "button" %>
                <%= link_to "Editar", edit_sport_path(sport), class: "btn btn-warning btn-sm", type: "button" %>
                <%= link_to "Eliminar", sport, method: :delete, data: { confirm: "¿Seguro que quieres eliminar este deporte? Se eliminarán todos los torneos asociados a él" }, class: "btn btn-danger btn-sm", type: "button" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/sports/new.html.erb
<% provide(:button_text, "Agregar") %>

<h1 align="center">Agregar Deporte</h1>

<%= render "form" %>

app/views/sports/show.html.erb
<h1 align="center"><%= @sport.name %></h1>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th colspan="6" scope="col" style="text-align: center;">
        Torneos: <%= @sport.tournaments.count %>
      </th>
    </tr>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Descripción</th>
      <th scope="col">Fecha de inicio</th>
      <th scope="col">Fecha de cierre</th>
      <th scope="col">Período</th>
      <th scope="col" style="text-align: right;">
        <%= link_to "Crear Torneo", new_sport_tournament_path(@sport) , class: "btn btn-primary btn-sm" %>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @sport.tournaments.each do |tournament| %>
      <tr>
        <td><%= tournament.name %></td>
        <td><%= tournament.description %></td>
        <td><%= tournament.registration_start_date %></td>
        <td><%= tournament.registration_end_date %></td>
        <td><%= tournament.period %></td>
        <td style="text-align: right;">
          <div class="btn-group" role="group" aria-label="User management">
            <%= link_to "Ver", tournament, class: "btn btn-info btn-sm", type: "button" %>
            <%= link_to "Editar", edit_sport_tournament_path(@sport, tournament), class: "btn btn-warning btn-sm", type: "button" %>
            <%= link_to "Eliminar", sport_tournament_path(@sport, tournament), method: :delete, data: { confirm: "¿Seguro que quieres eliminar este torneo?" }, class: "btn btn-danger btn-sm", type: "button" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>