config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  root to: 'welcome#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :admin do
    get 'landing', to: 'landing#index'

    resources :players
    resources :users
  end

  resources :pairings, only: [:edit, :update, :create, :destroy]
  resources :games, only: [:edit, :update]

  resources :schools, only: [:edit, :update, :index]
  resources :sports do
    resources :tournaments
  end

  resources :tournaments do
    resources :teams
  end
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :sport
  belongs_to :user

  has_many :teams, dependent: :destroy
  has_many :pairings, dependent: :destroy

  validates_presence_of :name
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_sport, only: [:new, :create, :destroy]
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]
  before_action :set_team, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    @pairing = Pairing.new
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = current_user.tournaments.new(tournament_params)
    @tournament.sport = @sport

    if @tournament.save
      redirect_to @tournament.sport, notice: 'Torneo creado correctamente.'
    else
      render :new
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    if @tournament.update(tournament_params)
      redirect_to @tournament, notice: 'Torneo editado correctamente.'
    else
      render :edit
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    redirect_to tournaments_url, alert: 'Torneo destruido.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    def set_sport
      @sport = Sport.find(params[:sport_id])
    end

    def set_team
      @team = Team.where("tournament_id = ?", @tournament.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :description, :registration_start_date, :registration_end_date, :period , :sport_id, :team_id, :user_id)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<div class="row justify-content-sm-center">
  <div class="col-sm-3">
    <div class="form-group">
      <%= form.label :name, "Nombre del Torneo" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="form-group">
      <%= form.label :description, "Descripción" %>
      <%= form.text_field :description, class: "form-control" %>
    </div>
  </div>
</div>

<div class="row justify-content-sm-center">
  <div class="col-sm-3">
    <div class="form-group">
      <%= form.label :registration_start_date, "Fecha de Inicio" %>
      <%= form.date_field :registration_start_date, class: "form-control" %>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="form-group">
      <%= form.label :registration_end_date, "Fecha de Finalización" %>
      <%= form.date_field :registration_end_date, class: "form-control" %>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="form-group">
      <%= form.label :period, "Período" %>
      <%= form.text_field :period, class: "form-control", placeholder: "Ej.: #{Time.now.year}-#{Time.now.year + 1}" %>
    </div>
  </div>
</div>

<div class="row justify-content-sm-center">
  <div class="col-sm-9">
    <%= form.submit yield(:button_text), class: "btn btn-primary" %>
  </div>
</div>

app/views/tournaments/_pairings.html.erb
<div class="row">
  <div class="col">
    <h3 align="center">Emparejamientos</h3>

    <%
      all_winners_set = true

      unless @tournament.pairings.empty?
        @tournament.pairings.first.games.each do |game|
          all_winners_set = false if game.winner_teams.empty?
        end
      end
    %>

    <% if all_winners_set && @tournament.pairings.empty? %>
      <%= form_for @pairing, html: { style: "text-align: center;" } do |form| %>
        <%= form.hidden_field :tournament_id, value: @tournament.id %>
        <%= form.submit "Emparejar Equipos", class: "btn btn-primary" %>
      <% end %>
    <% end %>

    <br>
    <%
      all_winners_set = []
      @tournament.pairings.each do |pairing|
        all_winners_set << true
      end
    %>
    <% @tournament.pairings.each_with_index do |pairing, i| %>
      <div class="row">
        <div class="col">
          <div align="center" class="row">
            <div class="col">
              <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#collapsePairing<%= i %>" aria-expanded="false" aria-controls="collapsePairing">
                <%= pairing.name || "Emparejamiento #{i + 1}" %>
              </button>
              <div class="btn-group" role="group" aria-label="Pairing management">
                <%= link_to "Editar", edit_pairing_path(pairing), class: "btn btn-success btn-sm", type: "button" %>
                <% if pairing == Pairing.last %>
                  <%= link_to "Eliminar", pairing, method: :delete, data: { confirm: "¿Seguro que quieres eliminarlo? Se eliminarán también los juegos de este emparejamiento" }, class: "btn btn-danger btn-sm", type: "button" %>
                <% end %>
              </div>
            </div>
          </div>
          <br>
          <div class="row collapse" id="collapsePairing<%= i %>">
            <% pairing.games.each do |game| %>
              <div class="col-sm-4">
                <div class="card bg-light">
                  <h5 class="card-header">
                    <div class="row">
                      <div class="col-sm-8">
                        <% unless game.winner_teams.empty? %>
                          Ganador: <%= game.winner_teams.first.name %>
                        <% else %>
                          Ganador: Por definir
                        <% end %>
                      </div>
                      <div align="right" class="col-sm-4">
                        <% unless game.teams.empty? || game.pairing.round_finished %>
                          <%= link_to "Editar", edit_game_path(game), class: "btn btn-success btn-sm" %>
                        <% end %>
                      </div>
                    </div>
                  </h5>
                  <div class="card-body">
                    <h5 align="center" class="card-text"><b>Equipos a enfrentarse</b></h5>
                    <p class="card-text">
                      <% unless game.teams.empty? %>
                        <div class="row">
                          <div align="right" class="col">
                            <div class="row">
                              <div class="col">
                                <%= game.teams.first.name %>
                              </div>
                            </div>
                            <div class="row">
                              <div class="col">
                                <% unless game.scores.empty? %>
                                  <%= game.scores.first.points %>
                                <% end %>
                              </div>
                            </div>
                          </div>
                          <div align="center" class="col-sm-2">
                            <div class="row">
                              <div class="col">
                                Vs.
                              </div>
                            </div>
                            <div class="row">
                              <div class="col">
                                -
                              </div>
                            </div>
                          </div>
                          <div class="col">
                            <div class="row">
                              <div class="col">
                                <%= game.teams.last.name %>
                              </div>
                            </div>
                            <div class="row">
                              <div class="col">
                                <% unless game.scores.empty? %>
                                  <%= game.scores.second.points %>
                                <% end %>
                              </div>
                            </div>
                          </div>
                        </div>
                      <% else %>
                        Sin enfrentamiento (el equipo clasifica a la siguiente ronda).
                      <% end %>
                    </p>
                  </div>
                  <div align="center" class="card-footer text-muted">
                    <% if game.start_date != nil && game.start_time != nil %>
                      <p class="card-text">Fecha del juego: <%= "#{game.start_date} #{game.start_time.strftime('%I:%M %p')}" %></p>
                    <% else %>
                      <% if game.teams.empty? %>
                        Fecha del juego: No aplica
                      <% else %>
                        <p class="card-text">Fecha del juego: Sin indicar</p>
                      <% end %>
                    <% end %>
                  </div>
                </div>
                <br>
              </div>
              <br>
              <% all_winners_set[i] = false if game.winner_teams.empty? %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <% if all_winners_set[i] && !pairing.round_finished && pairing.games.count > 1 %>
            <%= form_for @pairing, html: { style: "text-align: center;" } do |form| %>
              <%= form.hidden_field :tournament_id, value: @tournament.id %>
              <%= form.submit "Emparejar Equipos", class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tournaments/_teams.html.erb
<div class="row justify-content-sm-center">
  <div class="col-sm-10">
    <table class="table" style="text-align: center;">
      <thead class="thead-light">
        <tr>
          <th colspan="5" scope="col">Equipos: <%= @tournament.teams.count %></th>
        </tr>
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">Apodo</th>
          <th scope="col">Cantidad de Jugadores</th>
          <th scope="col">Creador</th>
          <th scope="col" style="text-align: right;">
            <% if @tournament.pairings.empty? %>
              <%= link_to "Agregar Equipo", new_tournament_team_path(@tournament), class: "btn btn-primary btn-sm" %>
            <% else %>
              <button type="button" class="btn btn-warning btn-sm" data-toggle="tooltip" data-placement="left" title="No puedes agregar equipos mientras haya emparejamientos vigentes">
                Agregar Equipo
              </button>
            <% end %>
          </th>
        </tr>
      </thead>

      <tbody>
        <% @tournament.teams.each do |team| %>
          <tr>
            <td><%= team.name %></td>
            <td><%= team.nickname %></td>
            <td><%= team.players.count %></td>
            <td><%= team.user.email %></td>
            <td style="text-align: right;">
              <div class="btn-group" role="group" aria-label="User management">
                <%= link_to "Ver", [@tournament, team], class: "btn btn-info btn-sm", type: "button" %>
                <%= link_to "Editar", edit_tournament_team_path(@tournament, team), class: "btn btn-success btn-sm", type: "button" %>
                <% if @tournament.pairings.empty? %>
                  <%= link_to "Eliminar", tournament_team_path(@tournament, team), method: :delete, data: { confirm: "¿Seguro que quieres eliminar este equipo? Los jugadores no se eliminarán del sistema" }, class: "btn btn-danger btn-sm", type: "button" %>
                <% else %>
                  <button type="button" class="btn btn-warning btn-sm" data-toggle="tooltip" data-placement="left" title="No puedes eliminar equipos mientras haya emparejamientos vigentes">
                    Eliminar
                  </button>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tournaments/_tournament_info.html.erb
<div class="row justify-content-sm-center">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h3 align="center" class="card-title">Información</h3>
        <p class="card-text"><b>Deporte:</b> <%= @tournament.sport.name %></p>
        <p class="card-text"><b>Descripción:</b> <%= @tournament.description %></p>
        <p class="card-text"><b>Fecha de inicio:</b> <%= @tournament.registration_start_date %></p>
        <p class="card-text"><b>Fecha de cierre:</b> <%= @tournament.registration_end_date %></p>
        <p class="card-text"><b>Período:</b> <%= @tournament.period %></p>
        <% unless @tournament.pairings.empty? || @tournament.pairings.last.games.last.winner_teams.empty? %>
          <h4 align="center" class="card-text"><b>Ganador</b></h4>
          <p align="center" class="card-text">
            <%= @tournament.pairings.last.games.last.winner_teams.first.name %>
          </p>
        <% end %>
        
        <div class="btn-group" role="group">
          <%= link_to "Editar", edit_tournament_path(@tournament), class: "btn btn-warning btn-sm card-link", type: "button" %>
          <%= link_to "Eliminar", @tournament, method: :delete, data: { confirm: "¿Seguro que quieres eliminar este torneo?" }, class: "btn btn-danger btn-sm", type: "button" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tournaments/edit.html.erb
<% provide(:button_text, "Modificar Torneo") %>
<%= render 'shared/errors', obj: @tournament %>

<h1 align="center">Modificar Torneo</h1>

<%= form_with(model: @tournament, local: true, url: sport_tournament_path(@tournament)) do |form| %>
  <%= render partial: 'form', locals: { form: form } %>
<% end %>

<div class="row">
  <div class="col">
    <%= link_to 'Atrás', :back %>
  </div>
</div>

app/views/tournaments/index.html.erb
<h1 align="center">Torneos Vigentes</h1>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Deporte</th>
      <th scope="col">Nombre</th>
      <th scope="col">Descripción</th>
      <th scope="col">Fecha de inicio</th>
      <th scope="col">Fecha de cierre</th>
      <th scope="col">Período</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= link_to tournament.sport.name, tournament.sport %></td>
        <td><%= tournament.name %></td>
        <td><%= tournament.description %></td>
        <td><%= tournament.registration_start_date %></td>
        <td><%= tournament.registration_end_date %></td>
        <td><%= tournament.period %></td>
        <td style="text-align: right;">
          <div class="btn-group" role="group" aria-label="User management">
            <%= link_to "Ver", tournament, class: "btn btn-info btn-sm", type: "button" %>
            <%= link_to "Editar", edit_sport_tournament_path(tournament.sport, tournament), class: "btn btn-warning btn-sm", type: "button" %>
            <%= link_to "Eliminar", sport_tournament_path(tournament.sport, tournament), method: :delete, data: { confirm: "¿Seguro que quieres eliminar este torneo?" }, class: "btn btn-danger btn-sm", type: "button" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%#= link_to 'New Tournament', new_sport_tournament_path %>

app/views/tournaments/new.html.erb
<% provide(:button_text, "Crear Torneo") %>
<%= render 'shared/errors', obj: @tournament %>

<h1 align="center">Crear Torneo</h1>

<%= form_with(model: @tournament, local: true, url: sport_tournaments_path(@sport)) do |form| %>
  <%#= render 'form', tournament: @tournament %>
  <%= render partial: 'form', locals: { form: form } %>
<% end %>

<div class="row justify-content-sm-center">
  <div class="col-sm-9">
    <%= link_to 'Atrás', :back %>
  </div>
</div>

app/views/tournaments/show.html.erb
<h1 align="center"><%= @tournament.name %></h1>

<%= render "tournament_info" %>

<hr>

<%= render "pairings" %>

<hr>

<%= render "teams" %>