config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  root to: 'welcome#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :admin do
    get 'landing', to: 'landing#index'

    resources :players
    resources :users
  end

  resources :pairings, only: [:edit, :update, :create, :destroy]
  resources :games, only: [:edit, :update]

  resources :schools, only: [:edit, :update, :index]
  resources :sports do
    resources :tournaments
  end

  resources :tournaments do
    resources :teams
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_roles, dependent: :destroy
  has_many :roles, through: :user_roles
  has_many :teams
  has_many :tournaments
  has_many :players

  # belongs_to :school, optional: true
  # belongs_to :period, optional: true

  # validates_presence_of :id_card, :first_name, :last_name, :email, on: [:update]

  def has_role?(role_name)
    roles.any? {|r| r.name == role_name.to_s}
  end

  def is_admin?
    has_role?("Administrador")
  end

  def is_delegate?
    has_role?("Delegado")
  end

  HUMANIZED_ATTRIBUTES = {
    :password => "Contraseña",
    :password_confirmation => "Confirmación de Contraseña",
    :email => "Correo",
    :user => "Usuario"
  }

  def self.human_attribute_name(attr, options = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :set_user, only: [:edit, :update, :show]
  before_action :get_roles, only: [:new, :edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to [:admin, @user]
    else
      @roles = Role.all
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to [:admin, @user]
    else
      @roles = Role.all
      render :edit
    end
  end

  def show
  end

  def index
    @users = User.all
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def get_roles
      @roles = Role.all
    end

    def user_params
      params.require(:user).permit(
        :email, :password, :password_confirmation, role_ids: []
      )
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   resource.build_phone unless resource.phone
  # end

  # PUT /resource
  # def update
  #   resource.phone.destroy if resource.phone
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(
  #     :account_update, keys: [
  #       :id_card, :first_name, :middle_name, :last_name, phone_attributes: [:number]
  #     ]
  #   )
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/views/admin/users/_form.html.erb
<div class="row">
  <div class="col">
    <div class="form-group">
      <%= f.label :email, "Correo Electrónico" %>
      <%= f.text_field :email, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "Ej.: juan.mendoza@gmail.com" %>
    </div>
  </div>
  <div class="col">
    <div class="form-group">
      <%= f.label :password, "Contraseña" %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="col">
    <div class="form-group">
      <%= f.label :password_confirmation, "Confirmación de Contraseña" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col">
    <legend>Roles de Usuario</legend>
    <% @roles.each do |role| %>
      <div class="property_form left span-9 last">
        <label>
          <%= check_box_tag "user[role_ids][]", role.id %>
          <%= role.name %>
        </label>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<%= render 'shared/errors', obj: @user %>

<h1 align="center">Edición de Usuario</h1>

<%= form_for @user, url: admin_user_path(@user) do |f| %>
  <%= render partial: '/admin/users/form', locals: { f: f } %>
  <%= f.submit "Editar Usuario", class: "btn btn-primary" %>
<% end %>

app/views/admin/users/index.html.erb
<h1 align="center">Usuarios</h1>

<div class="row justify-content-sm-center">
  <div class="col-sm-6">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Email</th>
          <th scope="col" style="text-align: right;"><%= link_to "Crear Usuario", new_admin_user_path, class: "btn btn-primary btn-sm" %></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td style="text-align: right;">
              <div class="btn-group" role="group" aria-label="User management">
                <%= link_to "Ver", [:admin, user], class: "btn btn-info btn-sm", type: "button" %>
                <% if current_user == user %>
                  <%= link_to "Editar", edit_user_registration_path, class: "btn btn-warning btn-sm", type: "button" %>
                <% else %>
                  <%= link_to "Editar", edit_admin_user_path(user), class: "btn btn-warning btn-sm", type: "button" %>
                <% end %>
                <%= link_to "Eliminar", admin_user_path(user), method: :delete, data: { confirm: "¿Seguro que quieres eliminar a este usuario?" }, class: "btn btn-danger btn-sm", type: "button" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<%= render 'shared/errors', obj: @user %>

<h1 align="center">Registro de Usuario</h1>

<%= form_for @user, url: admin_users_path(@user) do |f| %>
  <%= render partial: '/admin/users/form', locals: { f: f } %>
  <%= f.submit "Registrar Usuario", class: "btn btn-primary" %>
<% end %>

app/views/admin/users/show.html.erb
<div class="row">
  <div class="col">
    <h3 align="center"><%= @user.email %></h3>
  </div>
</div>