config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  root to: 'welcome#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :admin do
    get 'landing', to: 'landing#index'

    resources :players
    resources :users
  end

  resources :pairings, only: [:edit, :update, :create, :destroy]
  resources :games, only: [:edit, :update]

  resources :schools, only: [:edit, :update, :index]
  resources :sports do
    resources :tournaments
  end

  resources :tournaments do
    resources :teams
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.is_admin?
      can :manage, :all
    else
      can :read, :all
      if user.is_delegate?
        can :create, Team
      end
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :pairing

  has_many :team_games, dependent: :destroy
  has_many :teams, through: :team_games
  has_many :winner_team_games, dependent: :destroy
  has_many :winner_teams, through: :winner_team_games, class_name: "Team", source: :team
  has_many :scores, dependent: :destroy

  accepts_nested_attributes_for :scores
end

app/models/pairing.rb
class Pairing < ApplicationRecord
  belongs_to :tournament

  has_many :games, dependent: :destroy

  validates_presence_of :name, on: :update

  # Seleccionar los equipos a emparejar
  def select_teams
    team_ids = []

    if tournament.pairings.empty?
      tournament.teams.each do |team|
        team_ids << team.id
      end
    else
      tournament.pairings.each do |pairing|
        unless pairing.round_finished
          pairing.games.each do |game|
            game.winner_teams.each do |team|
              team_ids << team.id
            end
          end
          pairing.update_attribute(:round_finished, true)
        end
      end
    end

    team_ids
  end

  # Emparejamiento de equipos
  def match
    shuffled_team_ids = select_teams.shuffle
    total_teams = shuffled_team_ids.count

    if total_teams % 2 == 0
      even = true
    else
      even = false
    end

    for i in 1..(total_teams / 2)
      shuffled_team_ids -= pair = shuffled_team_ids.take(2)
      games.new(team_ids: [pair[0], pair[1]])
    end

    unless even
      games.new(winner_team_ids: [shuffled_team_ids.first])
    end
  end
end

app/models/period.rb
class Period < ApplicationRecord
  belongs_to :period_type
  has_many :users

  period_numbers = []

  for i in 1..10
    period_numbers.push i
  end

  PERIOD_NUMBERS = period_numbers
end

app/models/period_type.rb
class PeriodType < ApplicationRecord
  has_many :periods
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :phone_type, optional: true
  belongs_to :player

  validates_presence_of :number
end

app/models/phone_type.rb
class PhoneType < ApplicationRecord
  has_many :phones

  MOBILE = 'Móvil'
  HOME   = 'Casa'
  WORK   = 'Trabajo'

  PHONE_TYPES = [
    MOBILE,
    HOME,
    WORK
  ]
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :school
  belongs_to :period
  belongs_to :user

  has_one :phone, dependent: :destroy
  has_many :t_shirts, inverse_of: :player, dependent: :destroy
  has_many :player_teams, dependent: :destroy
  has_many :teams, through: :player_teams

  accepts_nested_attributes_for :phone, allow_destroy: true
  accepts_nested_attributes_for :t_shirts, allow_destroy: true

  validates_presence_of :id_card, :first_name, :last_name, :school_id, :period_id

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/player_team.rb
class PlayerTeam < ApplicationRecord
  belongs_to :player
  belongs_to :team
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles, dependent: :destroy
  has_many :users, through: :user_roles

  ADMIN       = 'Administrador'
  DELEGATE    = 'Delegado'
  PLAYER      = 'Jugador'

  ROLES = [
    ADMIN,
    DELEGATE,
    PLAYER
  ]
end

app/models/school.rb
class School < ApplicationRecord
  has_many :users
  accepts_nested_attributes_for :users
  
  # Facultad de Ciencias Ecpnómicas y Sociales
  ADMINISTRATION_AND_ACCOUNTING = "Administración y Contaduría"
  SOCIAL_SCIENCES = "Ciencias Sociales"
  ECONOMY = "Economía"

  # Facultad de Derecho
  LAW = "Derecho"

  # Facultad de Humanidades y Educación
  SOCIAL_COMMUNICATION = "Comunicación Social"
  EDUCATION = "Educación"
  PHILOSOPHY = "Filosofía"
  LETTERS = "Letras"
  PSYCHOLOGY = "Psicología"

  # Facultad de Ingeniería
  CIVIL = "Civil"
  INDUSTRIAL = "Industrial"
  COMPUTING = "Informática"
  TELECOMMUNICATIONS = "Telecomunicaciones"

  # Facultad de Teología
  THEOLOGY = "Teología"

  SCHOOLS = [
    ADMINISTRATION_AND_ACCOUNTING,
    SOCIAL_SCIENCES,
    ECONOMY,

    LAW,

    SOCIAL_COMMUNICATION,
    EDUCATION,
    PHILOSOPHY,
    LETTERS,
    PSYCHOLOGY,

    CIVIL,
    INDUSTRIAL,
    COMPUTING,
    TELECOMMUNICATIONS,

    THEOLOGY
  ]
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :game, optional: true
  belongs_to :team, optional: true
  belongs_to :player, optional: true
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :tournaments, dependent: :destroy

  validates_presence_of :name

  SOCCER = "Fútbol"
  INDOOR_FOOTBALL = "Fútbol Sala"
  BASKETBALL = "Básquetbol"
  VOLLEYBALL = "Vóleibol"
  BASEBALL = "Béisbol"
  PING_PONG = "Ping Pong"

  SPORTS = [
    SOCCER,
    INDOOR_FOOTBALL,
    BASKETBALL,
    VOLLEYBALL,
    BASEBALL,
    PING_PONG
  ]
end

app/models/t_shirt.rb
class TShirt < ApplicationRecord
  belongs_to :player, inverse_of: :t_shirts

  validates_presence_of :dorsal_number
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :tournament
  belongs_to :user

  has_many :player_teams, dependent: :destroy
  has_many :players, through: :player_teams
  has_many :team_games, dependent: :destroy
  has_many :games, through: :team_games
  # has_many :winner_team_games, dependent: :destroy
  # has_many :games, through: :winner_team_games

  accepts_nested_attributes_for :players

  validates_presence_of :name
end

app/models/team_game.rb
class TeamGame < ApplicationRecord
  belongs_to :team
  belongs_to :game
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :sport
  belongs_to :user

  has_many :teams, dependent: :destroy
  has_many :pairings, dependent: :destroy

  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_roles, dependent: :destroy
  has_many :roles, through: :user_roles
  has_many :teams
  has_many :tournaments
  has_many :players

  # belongs_to :school, optional: true
  # belongs_to :period, optional: true

  # validates_presence_of :id_card, :first_name, :last_name, :email, on: [:update]

  def has_role?(role_name)
    roles.any? {|r| r.name == role_name.to_s}
  end

  def is_admin?
    has_role?("Administrador")
  end

  def is_delegate?
    has_role?("Delegado")
  end

  HUMANIZED_ATTRIBUTES = {
    :password => "Contraseña",
    :password_confirmation => "Confirmación de Contraseña",
    :email => "Correo",
    :user => "Usuario"
  }

  def self.human_attribute_name(attr, options = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Deportes UCAB</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="deportesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Deportes</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="deportesDropdown">
          <% Sport.all.each do |s| %>
            <%= link_to s.name, s, class: "dropdown-item" %>
          <% end %>
          <% if can? :manage, Sport %>
            <div class="dropdown-divider"></div>
<<<<<<< HEAD:app/views/shared/_header.html.erb
            <%= link_to "Agregar", "#", class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <% if can? :manage, User %>
        <li class="nav-item">
          <a class="nav-link" href="#">Jugadores</a>
=======
            <%= link_to "Ver Todos", sports_path, class: "dropdown-item" %>
            <%= link_to "Agregar", new_sport_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Torneos", tournaments_path, class: "nav-link" %>
      </li>
      <% if can? :manage, Player %>
        <li class="nav-item">
          <%= link_to "Jugadores", admin_players_path, class: "nav-link" %>
        </li>
      <% end %>
      <% if can? :manage, User %>
        <li class="nav-item">
          <%= link_to "Usuarios", admin_users_path, class: "nav-link" %>
>>>>>>> master:app/views/layouts/_header.html.erb
        </li>
      <% end %>
    </ul>

    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item dropleft">
          <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <div class="dropdown-menu" aria-labelledby="profileDropdown">
<<<<<<< HEAD:app/views/shared/_header.html.erb
            <%= link_to "Mi Perfil", profile_path, class: "dropdown-item" %>
            <%= link_to "Solicitudes de Registro", "#", class: "dropdown-item" %>
=======
            <%= link_to "Editar Perfil", edit_user_registration_path, class: "dropdown-item" %>
>>>>>>> master:app/views/layouts/_header.html.erb
            <div class="dropdown-divider"></div>
            <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Iniciar Sesión", new_user_session_path, class: "nav-link" %>
        </li>
        <!-- <li class="nav-item">
          <%#= link_to "¡Regístrate!", new_user_registration_path, class: "nav-link" %>
        </li> -->
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
 <% if notice || alert%>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
            <%= value %>
  </div>
 <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeportesUcab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
      <%= render 'layouts/messages' %>
    </header>
    <div class="container">
      <main>
        <%= yield %>
      </main>
    </div>
    <footer></footer>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            impidieron a este <%= obj.class.to_s.downcase %> registrarse:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Deportes UCAB</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="deportesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Deportes</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="deportesDropdown">
          <% Sport.all.each do |s| %>
            <%= link_to s.name, s, class: "dropdown-item" %>
          <% end %>
          <% if can? :manage, Sport %>
            <div class="dropdown-divider"></div>
            <%= link_to "Agregar", "#", class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <% if can? :manage, Player %>
        <li class="nav-item">
          <%= link_to "Jugadores", admin_players_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>

    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item dropleft">
          <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <div class="dropdown-menu" aria-labelledby="profileDropdown">
            <%= link_to "Mi Perfil", profile_path, class: "dropdown-item" %>
            <% if can? :manage, User %>
            <%= link_to "Crear Delegado", "#", class: "dropdown-item" %>
            <% end %>
            <div class="dropdown-divider"></div>
            <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Iniciar Sesión", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "¡Regístrate!", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>